import type { Metadata } from 'next';

import { Layout } from '@packages/layout';

import { AppProvider } from '@/context/AppContext';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <AppProvider>{children}</AppProvider>
    </Layout>
  );
}
