export const questions = [
  'Que el sindrome de Down fuera contagioso',
  'Que cada vez que una multitud de personas cante Sweet Caroline cada Pa Pa Pa baje IQ del mundo en un 1 punto',
  'Que cada vez que el 11s es mencionado tengas que negarlo usando como prueba un video en reversa del avion estrellando la torre',
  'Que niegues el holocausto tan fuertemente que escribes un libro: "The Liary of Ana Frank"',
  'Que tengas que pedir perdón por la esclavitud (en publico) cada vez que compres algo que contenga algodón',
  'Que tengas que empezar cada conversación que tengas con una mujer con "No soy un peligro para ti"',
  'Que cada vez que veas a una persona con discapacidad tengas que imitarla',
  'Que cada vez que veas a una embarazada tengas que tocarle la tripa como si fueran unos bongos',
  'Que siempre que hables con un paciente de quimio tengas que quejarte de un mal corte de pelo',
  'Que cada vez que te llegue una factura a casa tengas que escribir una carta de 2 paginas a Pedro Sanchez agradeciéndole que haya traído prosperidad económica a tu vida',
  'Que solo puedas mear en baños públicos y tengas que bajarte siempre los pantalones por los tobillos',
  'Que solo puedas cagar en casa pero tienes que hacerlo firme, de pie, delante del retrete y rezando por que atine',
  'Que se te abra la maleta en mitad de un aeropuerto concurrido y salgan un montón de dildos y vibradores encendidos rebotando por todo el suelo',
  'Que cada vez que haya un bicho en casa, llames a la policia para que vengan a matarlo',
  'Que te crezca un mini brazo de la frente que no pare de hacer el saludo Nazi',
  'Que tengas los ojos y los pezones cambiados (pezones en la cara y ojos en el pecho)',
  'Que cada vez que alguien te pregunte por un consejo, tengas que darle una cita aleatoria de Hitler',
  'Que cada vez que alguien llore a tu alrededor tengas que recolectar sus lagrimas en una recipiente y decirle "voy a llevar estas lagrimas a la oficina de nenazas"',
  'Que tengas que hacerte la vasectomía pero la única experiencia de tu doctor es el juego de "Operación"',
  'Que seas acusado en falso de un asesinato, pero tu abogada es "Kim Kardashian"',
  'Que cada vez que veas a una mujer, te venga la cifra de cuanto pesa (mágicamente) y tengas que gritársela (estilo síndrome de tourette)',
  'Que cada vez que veas a una persona en silla de ruedas tengas que pegarle un puñetazo en la pierna para verificar si lo siente o lo esta fingiendo',
  'Que tengas que ir a un Hospital psiquiátrico y convencer a los enfermos que llevas toda la vida viviendo en las paredes',
  'Que tengas que ir a una unidad de Quemados críticos en un hospital y decir "¿Hace calor aquí o soy yo?"',
  'Que cada vez que te hagan un análisis de próstata te corras (sin placer)',
  'Que la primera vez que te hagas un análisis de próstata el médico te cuente lo fácil que fue meter su pene ahí',
  'Que cada vez que des un paso, un edificio de un país del tercer mundo colapse',
  'Que hackees el móvil de un fallecido y le envies un mensaje a sus seres queridos diciendo que fingiste tu muerte para huir del país y que no te contacten mas',
  'Que cada vez que confundas el genero de una persona tengas que demostrarle que no eres transfobo describiendo la lista de los 600 generos y sus pronombres',
  'Que cada vez que comas algo, la misma cantidad de calorias, instantáneamente se desaparezcan del estomago del africano desnutrido que haya comido más recientemente',
  'Que pierdas 3cm',
  'Que escribas un nuevo libro que se llame "12, los nuevos 18" y tenés que enviarle una copia a todos tus contactos',
  'Que cada vez que entres en una tienda y el cajero se vea extranjero se te escape un "este país se va a la mierda" y salir de la tienda',
  'Que salgas en la lista de Jeffrey Epstein',
  'Que salgas en los audios de Koldo',
  'Que tengas que ir a un funeral a pedirle a la viuda los 10 euros que te debía el difunto',
  'Que tengas que tatuarte la cara de Irene Montero en grande en la Nalga',
  'Que cada vez que veas a un artista callejero, tengas que robarle las monedas y decirle: "Es por tu bien, para que busques un trabajo de verdad"',
  'Que cada vez que veas a alguien comiendo una ensalada, tengas que escupir dentro y decir: "Faltaba el aderezo del chef"',
  'Que tengas que ir a una clínica de fertilidad y ofrecerte como "donante de repuesto" a las parejas que salen',
  'Que tengas que dar un discurso en una boda explicando detalladamente por qué crees que el divorcio llegará antes de un año',
  'Que tengas que confesarle a tus suegros que tu mayor fantasía sexual involucra a su mascota y un disfraz de superhéroe',
  'Que cada vez que veas a un niño con un helado, tengas que darle un lametón y salir corriendo',
  'Que cada vez que alguien te dé la mano, tengas que chuparte los dedos justo después de soltarlo',
  'Que cada vez que pases por un hospital infantil, tengas que gritar por la ventana: "¡Aprovechad, que se acaba el tiempo!"',
  'Que cada vez que veas a un ciego, tengas que moverle los muebles de sitio y decirle "un laberinto real"',
  'Que cada vez que veas a una persona con Alzheimer, tengas que contarle que le debes 500 euros y que hoy es el día de pago',
  'Que cada vez que veas a una persona asiática, tengas que preguntarle si el perro de tu vecino está a salvo con ellos',
  'Que tengas que proponer un brindis en el funeral de tu abuela agradeciendo que por fin "se ha liberado la herencia"',
  'Que cada vez que veas a una persona negra, tengas que preguntarle si conoce a los actores del anuncio de Cola-Cao',
  'Que tengas que pedirle matrimonio a tu pareja usando un anillo que le robaste a un cadáver en un tanatorio',
  'Que cada vez que veas a un judío, tengas que preguntarle si el gas de su cocina es natural o "de los de antes"',
  'Que tengas que dar una clase de educación sexual usando solo fotos de tus padres follando',
  'Que cada vez que veas a un veterano de guerra sin piernas, tengas que preguntarle si "se ahorra mucho en calcetines"',
  'Que tengas que ir a un centro de desintoxicación y regalar botellitas de Jägermeister como "kit de bienvenida"',
  'Que cada vez que vayas a un museo y tengas que preguntar "¿Dónde esta la sección de Arte de dictadores incomprendidos?"',
  'Que tengas que convencer a un huérfano de que sus padres no murieron, sino que se cambiaron de nombre para no volver a verlo',
  'Que cada vez que veas a una mujer amamantando, tengas que acercarte con cualquier recipiente y decir: "¿Te sobra un poco?"',
  'Que el Alzheimer sea una enfermedad de transmisión sexual',
  'Que las cenizas de difuntos fueran el potenciador de sabor adictivo de la comida rápida',
  'Que la única forma de curar el cáncer sea transfiriéndoselo a un huérfano al azar',
  'Que las erecciones emitan el sonido de una corneta',
  'Que el SIDA te dé superpoderes físicos, pero solo durante los últimos 10 minutos de vida',
  'Que la pedofilia sea un efecto secundario obligatorio de cumplir los 60 años',
  'Que las personas en silla de ruedas tengan un contador de velocidad obligatorio que grite "¡MÍRAME, VOY VOLANDO!" si pasan de los 5 km/h',
  'Que el efecto secundario del Ibuprofeno sea que te crezcan pezones funcionales en las palmas de las manos durante 2 horas',
  'Que cada vez que te cruces con alguien con un tono de piel diferente al tuyo, tengas que comprobar si "destiñe" frotándole fuerte con una toallita húmeda',
  'Que el efecto secundario de comer comida china sea que tus ojos se achinen un 1% más cada vez',
  'Que cada vez que veas a un grupo de turistas chinos, tengas que ponerte delante de ellos y empezar a hacer movimientos de karate aleatorios',
  'Que el resto de tu vida que cada vez que veas un desnudo tu cerebro pixela las partes obscenas como en la censura japonesa',
  'Que cada vez que alguien hable del Covid tengas que defender que en realidad una campaña de marketing de AliExpress que se les fue de las manos',
  'Que cada vez que veas a un asiático tocando el piano, tengas que pegarle en las manos y decirle: "¡Más rápido, que tu padre no te va a querer!"',
  'Que las personas con enanismo exploten si las abrazas demasiado fuerte',
  'Que los testículos brillaran como bombillas cuando tienes ganas de orinar',
  'Que cada vez que tengas un orgasmo, tu padre reciba una notificación push en el móvil',
  'Que los juguetes sexuales solo funcionen si los bendice un cura en presencia de tus suegros',
  'Que la virginidad se pierda obligatoriamente con el miembro más anciano de la familia',
  'Que el vello púbico de tus padres fuera el único material legal para rellenar tus almohadas',
  'Que cada vez que tengas una fantasía sexual, aparezca como hilo en el grupo de WhatsApp de la familia',
  'Que los juguetes eróticos fueran heredables por testamento y de uso obligatorio',
  'Que el sexo anal fuera la única forma legal de pedir perdón a un hermano',
  'Que las ETS fueran coleccionables como cartas Pokémon para subir de estatus social',
  'Que el sexo con ancianos fuera considerado un servicio a la comunidad obligatorio al cumplir los 18 (como la mili)',
  'Que la necrofilia fuera legal, pero solo con familiares',
  'Que el pene/vagina tuviera dientes de leche que se caen durante la pubertad',
  'Que cada vez que veas un juguete sexual, sientas el impulso de enseñárselo a tu jefe',
  'Que tu despertador sea la voz de Begoña Gómez leyéndote un programa de máster en transformación social competitiva',
  'Que cada vez que veas a un policía, tengas que enseñarle la Ley de Amnistía subrayada y decirle: "Técnicamente, hoy no puedes multarme por mis valores"',
  'Que tu único abogado para un juicio por asesinato sea Óscar Puente y su estrategia de defensa sea insultar al juez por Twitter (X) a las 3 de la mañana',
  'Que cada vez que Sánchez "cambie de opinión", a ti se te borre un recuerdo de tu infancia'
];
